name: Deploy Jokatech Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Build do site
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Enviar site
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publicar
        uses: actions/deploy-pages@v1
